"""create initial schema

Revision ID: 682e4245ba46
Revises:
Create Date: 2026-07-24 22:03:15.387708
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "682e4245ba46"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cinemas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kino_cinema_id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kino_cinema_id"),
    )
    with op.batch_alter_table("cinemas", schema=None) as batch_op:
        batch_op.create_index("ix_cinemas_city_id", ["city_id"], unique=False)

    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kino_movie_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("name_rus", sa.String(length=500), nullable=True),
        sa.Column("name_origin", sa.String(length=500), nullable=True),
        sa.Column("normalized_names", sa.JSON(), nullable=False),
        sa.Column("premiere_date", sa.Date(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("is_pre_sales", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kino_movie_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("default_city_id", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_telegram_id"), ["telegram_id"], unique=True)

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creation_key", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kino_movie_id", sa.Integer(), nullable=True),
        sa.Column("movie_title", sa.String(length=500), nullable=True),
        sa.Column("movie_original_title", sa.String(length=500), nullable=True),
        sa.Column("raw_query", sa.String(length=500), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("tracking_mode", sa.String(length=32), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=True),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column("cinema_scope", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_before_error", sa.String(length=32), nullable=True),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_errors", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "tracking_mode != 'DATE_RANGE' OR (date_from IS NOT NULL AND date_to IS NOT NULL)",
            name="ck_subscription_date_range",
        ),
        sa.CheckConstraint(
            "tracking_mode != 'EXACT_DATE' OR date_from = date_to",
            name="ck_subscription_exact_date",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("creation_key"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_subscriptions_city_mode", ["city_id", "tracking_mode"], unique=False
        )
        batch_op.create_index(
            "ix_subscriptions_status_next_check", ["status", "next_check_at"], unique=False
        )
        batch_op.create_index("ix_subscriptions_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_table(
        "seen_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("source_session_key", sa.String(length=255), nullable=False),
        sa.Column("kino_session_id", sa.Integer(), nullable=True),
        sa.Column("kino_cinema_id", sa.Integer(), nullable=True),
        sa.Column("session_date", sa.Date(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "subscription_id", "source_session_key", name="uq_seen_subscription_session"
        ),
    )
    op.create_table(
        "subscription_cinemas",
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("kino_cinema_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subscription_id", "kino_cinema_id"),
    )
    op.create_table(
        "subscription_rejected_movies",
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("kino_movie_id", sa.Integer(), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subscription_id", "kino_movie_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_rejected_movies")
    op.drop_table("subscription_cinemas")
    op.drop_table("seen_sessions")
    op.drop_table("notifications")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index("ix_subscriptions_user_status")
        batch_op.drop_index("ix_subscriptions_status_next_check")
        batch_op.drop_index("ix_subscriptions_city_mode")

    op.drop_table("subscriptions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_telegram_id"))

    op.drop_table("users")
    op.drop_table("movies")
    with op.batch_alter_table("cinemas", schema=None) as batch_op:
        batch_op.drop_index("ix_cinemas_city_id")

    op.drop_table("cinemas")
    # ### end Alembic commands ###
